version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: chatbot_db
    restart: always
    environment:
      POSTGRES_DB: chatbot_db
      POSTGRES_USER: chatbot_user
      POSTGRES_PASSWORD: chatbot_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - chatbot_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: chatbot_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@chatbot.local
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - chatbot_network

volumes:
  postgres_data:

networks:
  chatbot_network:
    driver: bridge 